---
title: "3-SA-meta-analyis.Rmd"
author: "Seth Green"
date: "8/19/2020"
output: html_document
---


The quantitative review will aggregate individual data from all participants and, when necessary, will estimate intent-to-treat effects rather than treatment effects on the treated (in keeping with our emphasis on policy-relevant effects). The planned analytic approach is random-effects meta-analysis; the treatments are heterogeneous, as are the populations. 
Our intended statistical approach is frequentist. The main outcomes of interest are which interventions, and in which populations, treatments have the strongest effects; we will also assess quality of evidence overall with respect to possibilities of publication bias, internal validity of studies, reliability and noisiness of dependent variables, and ultimately ease of high-fidelity implementation. We will attempt this quantitatively where possible and qualitatively where not.
Tests for publication bias will follow those in ‘The contact hypothesis re-evaluated', https://doi.org/10.1017/bpp.2018.25.
Statistical analyses will be conducted in R, drawing from the CRAN view page on meta-analysis  (https://cran.r-project.org/web/views/MetaAnalysis.html) or functions of our own creation when needed.
Statistical heterogeneity is expected. Available covariates are likely to vary widely, so with the exceptions of population and setting of intervention, any moderator analysis is speculative.

Analysis of subgroups or subsets: We will compare subsets of the data according to classifications of evaluation methodology (i.e., observational vs. quasi-experimental vs. experimental methods) and of outcome measurement (i.e., general behavior indices vs. perpetration behavior, and attitudinal measurement vs. behavioral measurement). 
Evaluate the overall effect size of behavioral outcomes for all of the studies in the dataset, both in the short- and in the long-term. 
Compare the effect size of behavioral outcomes for experimental and quasi-experimental studies vs. non-experimental observational studies, both in the short- and in the long-term. 
Compare the effect size of behavioral outcomes for studies with random assignment vs. quasi-experimental studies, both in the short- and in the long-term. 
Evaluate at the effect size of perpetration behavioral outcomes for only studies with random assignment, both in the short- and in the long-term. 
Compare the effect size of behavioral outcomes and attitudinal outcomes, both in the short- and long-term, among the quasi-experimental and randomly-assigned studies. (The covariation of attitudes and behaviors will be assessed in the full sample of studies.)

Analysis plan discussed 
what is the average effect size:
RCT – behavior
RCT – attitude
RCT+Quasi – behavior
RCT+Quasi – attitude
Everything – behavior
Everything – attitude
What is the association between attitudes and behaviors (temporal match) – this answers our question of ‘should we care about attitudes?’. We are only looking at studies that measure both attitudes and behavior in their outcomes. 
